### PR TITLE
Rename function for jumping

### PR DESCRIPTION
**Pull request by limitedeternity**
`QuicktexJump` -> `quicktex#DoJump`

### CODE REVIEW

**Comment by brennier** [comment]
What's the purpose of renaming this function?

If you want to autoload the function, it needs to be under the autoload folder.

**Comment by limitedeternity** [comment]
The purpose is to mark this function as "exported from module" using a namespace.

This way, when you write a `<Space>` mapping for keyword dictionary, it's obvious where does this function come from.

You didn't mean this function to be considered "private", right?

**Comment by limitedeternity** [comment]
By the way, documentation mentions `g:quicktex_always_tex` variable, which is actually `g:quicktex_always_latex`

**Comment by brennier** [comment]
I like the idea. And thanks for letting me know about `g:quicktex_always_tex`. I'll fix the documentation soon.

**Comment by brennier** [comment]
Fixed. Thanks for your help!

**Pull request merged**
